apiVersion: v1
kind: Service
metadata:
  name: bootcamp-devops-web-svc
  labels:
    app: bootcamp-devops-web
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5173
  selector:
    app: bootcamp-devops-web
  type: ClusterIP
