bootcamp-devops-apiVersion: v1
kind: Service
metadata:
  name: bootcamp-devops-api-svc
  labels:
    app: bootcamp-devops-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: bootcamp-devops-api
  type: ClusterIP
