bootcamp-devops-apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp-devops-api
spec:
  selector:
    matchLabels:
      app: bootcamp-devops-api
  template:
    metadata:
      labels:
        app: bootcamp-devops-api
    spec:
      containers:
        - name: bootcamp-devops-api
          image: "abalderasp/bootcamp-devops-api-dev"
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
