apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootcamp-devops-api-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bootcamp-devops-api-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/bootcamp-devops-api/development
    repoURL: https://github.com/devops-bootcamp-sre/bootcamp-devops-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true