apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp-devops-web
spec:
  selector:
    matchLabels:
      app: bootcamp-devops-web
  template:
    metadata:
      labels:
        app: bootcamp-devops-web
    spec:
      containers:
        - name: bootcamp-devops-web
          image: "gitopsdevopsbootcamp/bootcamp-devops-web-dev"
          ports:
            - containerPort: 5173
              name: http
              protocol: TCP
