apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: abalderasp/bootcamp-devops-api
  newName: abalderasp/bootcamp-devops-api
  newTag: 54d08402d7b9e3708f1b4dbad2ba3862eee7ab50
